import type { Metadata } from "next";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import { IBM_Plex_Sans_Thai } from "next/font/google";
import "./globals.css";
import "aos/dist/aos.css";

const IBM = IBM_Plex_Sans_Thai({
  subsets: ["latin", "thai"],
  weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  title: "S-ONE SERVICE",
  description: "Generated by create next app",
  // icons: {
  //   icon: "/icons/SOne_icon.png",
  //   shortcut: "/icons/SOne_icon.png",
  //   apple: "/icons/SOne_icon.png",
  // },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${IBM.className} antialiased`}>
        <Navbar />
        <div className="min-h-screen">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
